#!/usr/bin/env bash

# install our "PPA", currently points to virtualbox
echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list

# add Tuffix PPA gpg key
