#!/usr/bin/env bash

# GOAL: install pre requisites for the Tuffix installer
# AUTHOR: Jared Dyreson
# INSTITUTION: California State University Fullerton

sudo pip3 install "git+https://github.com/mshafae/tuffix#egg=httpie"
