
---

#####################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: deb_architecture
    
    - name: Update repositories cache and update all packages to the latest version
      apt:
        update_cache: yes
        #upgrade: dist

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    #- name: Ensure that the vboxsf group exists to premptively add the user to it.
    #  group:
    #    name: vboxsf
    #    state: present

    - name: Kitchen sink packages
      apt:
        pkg:
          - curl
          - enscript
          - gpg
          - synaptic
          - vim
          - libreadline-dev
          - manpages-posix
          - manpages-posix-dev
          - glibc-doc
          - nfs-common
          #- a2ps
          #- chromium-browser
          #- dkms
          #- emacs
          #- gthumb
          #- openssh-client
          #- openssh-server
          #- seahorse
          #- vim-gtk3

#####################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  vars:
    login: student
  tasks:

    - name: Clang toolchain (default version for target)
      apt:
        pkg:
          - build-essential
          - clang
          - clang-tidy
          - clang-format
          - lldb

    - name: G++ compiler (default version for target)
      apt:
        pkg:
          - build-essential
          - gcc
          - g++
          - gdb

    # https://code.visualstudio.com/docs/setup/linux
    #- name: VSCode Editor
    #  apt: deb=https://go.microsoft.com/fwlink/?LinkID=760868

    #- name: Atom editor
    #  apt: deb=https://atom.io/download/deb

    #- name: Atom gdb support
    #  command: /usr/bin/apm install dbg-gdb dbg output-panel

    # this playbook is run as root, so the apm command above
    # creates a ~/.atom owned by root, so the student user does
    # not have permissions into it, and Atom fails to load
    # properly and shows a debug interface. This makes the
    # directory owned by {{ login }}, by default `student`, thus
    # solving the problem.
    #- name: atom owned by user instead of root
    #  file:
    #    path: ~/.atom
    #    owner: "{{ login }}"
    #    group: "{{ login }}"

    #- name: Adding current user {{ login }} to group vboxsf preemptively
    #  user:
    #    name: "{{ login }}"
    #    groups: vboxsf
    #    append: yes

    - name: Source code control
      apt:
        pkg:
          - git
          - subversion

    - name: Google Test and Google Mock
      apt:
        pkg:
          - libgtest-dev
          - libgmock-dev
          - cmake

    - name: Google Mock Library Build (builds Google Test Library as a dependency)
      shell: |
        BUILDDIR="/tmp/gmockbuild.$$"
        DESTROOT="/usr/local/"
        mkdir -p ${BUILDDIR}
        cd ${BUILDDIR}
        cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/googletest/googlemock
        make
        mkdir -p ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgtest.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgtest_main.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgmock.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgmock_main.a ${DESTROOT}/lib

    - name: additional C++ libraries and tools
      apt:
        pkg:
          - autoconf
          - automake
          - cimg-dev
          - libc++-dev
          - libc++abi-dev
          - nlohmann-json3-dev
          #- cscope
          #- libboost-all-dev
          #- libfccp-dev
          #- libsqlite3-dev
          #- libssl-dev
          #- meld
          #- sqlite3
          #- valgrind

#####################################################################
# Bazel & Microsoft VS Code
# point person: Michael Shafae
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Prerequisites for Bazel
      apt:
        pkg:
          - curl
          - gnupg

    - name: Bazel binary from koenvervloesem
      shell: |
        DESTROOT="/usr/local/"
        BAZEL="bazel-3.7.2"
        curl https://github.com/koenvervloesem/bazel-on-arm/releases/download/v3.7.2/bazel-3.7.2 -O /tmp/${BAZEL}
        mkdir -p ${DESTROOT}/bin
        install -o root -g root -m 755 /tmp/${BAZEL} ${DESTROOT}/bin
        ln -s ${DESTROOT}/bin/${BAZEL} ${DESTROOT}/bin/bazel

    - name: VSCode Editor
      apt: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-{{ deb_architecture.stdout }}


#####################################################################
# cleanup
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: apt clean
      command: apt clean

...
