
---

#####################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:
  
    - name: Update repositories cache and update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: 'yes'
        #upgrade: dist

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Ensure that the vboxsf group exists to premptively add the user to it.
      group:
        name: vboxsf
        state: present

    - name: Kitchen sink packages
      apt:
        pkg:
          - curl
          - enscript
          - gpg
          - openssh-client
          - openssh-server
          - synaptic
          - vim
          - libreadline-dev
          - manpages-posix
          - manpages-posix-dev
          - glibc-doc
          - nfs-common
          - graphicsmagick
          - libgraphicsmagick++1-dev
          - doxygen
          - valgrind
          #- a2ps
          #- chromium-browser
          #- dkms
          #- emacs
          #- gthumb
          #- seahorse
          #- vim-gtk3

#####################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  vars:
    login: student
  tasks:

    - name: Clang toolchain
      apt:
        pkg:
          - build-essential
          - clang
          - clang-tidy
          - clang-format
          - lldb

    - name: G++ compiler (default version for target Ubuntu release)
      apt:
        pkg:
          - build-essential
          - gcc
          - g++
          - gdb

    - name: Adding current user {{ login }} to group vboxsf preemptively
      user:
        name: "{{ login }}"
        groups: vboxsf
        append: yes

    - name: Source code control
      apt:
        pkg:
          - git
          - subversion

    - name: Google Test and Google Mock
      apt:
        pkg:
          - libgtest-dev
          - libgmock-dev
          - cmake

    - name: Google Mock Library Build (builds Google Test Library as a dependency)
      shell: |
        BUILDDIR="/tmp/gmockbuild.$$"
        DESTROOT="/usr/local/"
        mkdir -p ${BUILDDIR}
        cd ${BUILDDIR}
        cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/googletest/googlemock
        make
        mkdir -p ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgtest.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgtest_main.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgmock.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgmock_main.a ${DESTROOT}/lib

    - name: additional C++ libraries and tools
      apt:
        pkg:
          - autoconf
          - automake
          - libc++-dev
          - libc++abi-dev
          - nlohmann-json3-dev
          - libyaml-cpp-dev
          #- cscope
          #- libboost-all-dev
          #- libfccp-dev
          #- libsqlite3-dev
          #- libssl-dev
          #- meld
          #- sqlite3
          #- valgrind


#####################################################################
# CPSC 240
# point person: Floyd Holliday
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 240 assembly environment
      apt:
        pkg:
          - intel2gas
          - nasm

#####################################################################
# Linux Zoom Client (AMD64 only)
# point person: Michael Shafae
#####################################################################
- hosts: all
  remote_user: root
  tasks:
    
    - name: Zoom Client Prerequisites
      apt:
       pkg:
         - libglib2.0-0
         - libgstreamer-plugins-base1.0-0
         - libxcb-shape0
         - libxcb-shm0
         - libxcb-xfixes0
         - libxcb-randr0
         - libxcb-image0
         - libfontconfig1
         - libgl1-mesa-glx
         - libxi6
         - libsm6
         - libxrender1
         - libpulse0
         - libxcomposite1
         - libxslt1.1
         - libsqlite3-0
         - libxcb-keysyms1
         - libxcb-xtest0
         - ibus

    - name: Linux Zoom Client (AMD 64)
      apt:
       deb: https://zoom.us/client/latest/zoom_amd64.deb

#####################################################################
# GitHub's gh utility
# point person: Michael Shafae
#####################################################################

    - name: Prerequisites for GitHub's gh
      apt:
        pkg:
          - dirmngr
          - software-properties-common

    - name: gh client distribution URI as package source (i386, amd64, arm64)
      shell: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      args:
        warn: false

    - name: Update repositories cache
      apt:
        update_cache: yes
    
    - name: GitHub gh
      apt:
        pkg:
          - gh

#####################################################################
# Bazel & Microsoft VS Code
# point person: Michael Shafae
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Prerequisites for Bazel
      apt:
        pkg:
          - curl
          - gnupg

    - name: Get Bazel Repository GPG Key
      get_url:
        url: https://bazel.build/bazel-release.pub.gpg
        dest: /tmp/bazel-release.pub.gpg
    
    - name: Add Bazel GPG key to trusted keys and add the PPM to the APT source list
      shell: |
        cat /tmp/bazel-release.pub.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/bazel.gpg
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list

    - name: Update repositories cache
      apt:
        update_cache: yes
    
    - name: Bazel
      apt:
        pkg:
          - bazel

    - name: Prerequisites for VS Code
      apt:
        pkg:
          - libnss3
          - gnupg
          - libxkbfile1
          - libsecret-1-0
          - libgtk-3-0
          - libxss1
          - libgbm1

    # https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    # https://go.microsoft.com/fwlink/?LinkID=760868
    - name: VS Code Editor for AMD64
      apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        
#####################################################################
# Discord and Slack
# point person: Daniel Reisch
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Install Discord
      snap:
        name: discord
        classic: yes

    - name: Install Slack
      snap:
        name: slack
        classic: yes

#####################################################################
# Remove Update Manager
# point person: Daniel Reisch 
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Remove update-manager
      apt:
        name: update-manager
        state: absent

#####################################################################
# cleanup
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: apt clean
      command: apt clean

...
