
---

###############################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Update repositories cache and update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Ensure that the vboxsf group exists to premptively add the user to it.
      group:
        name: vboxsf
        gid: 999
        state: present

    - name: kitchen sink packages
      apt: name={{item}} state=present
      with_items:
        - a2ps
        #- cifs-utils
        - chromium-browser
        - curl
        #- default-jdk
        - dkms
        #- eclipse
        - emacs
        #- gnupg2
        #- pgpgpg
        - graphviz
        - gthumb
        #- lynx
        #- octave
        - openssh-client
        - openssh-server
        #- racket
        - seahorse
        - stow
        - synaptic
        - vagrant
        - vim
        - xfce4-goodies
        - xfce4-weather-plugin

###############################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: g++ 5 compiler
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - gcc-5
        - g++-5

    - name: gdb debugger
      apt: name=gdb state=present

    - name: Atom editor
      apt: deb=https://atom.io/download/deb

    - name: Atom gdb support
      command: /usr/bin/apm install dbg-gdb dbg output-panel

    # this playbook is run as root, so the apm command above creates a ~/.atom
    # owned by root, so the student user does not have permissions into it, and
    # Atom fails to load properly and shows a debug interface. This makes the
    # directory owned by {{ login }}, by default `student`, thus
    # solving the problem.
    - name: .atom owned by user instead of root
      file:
        path: ~/.atom
        owner: "{{ login }}"
        group: "{{ login }}"

    - name: Adding current user {{ login }} to group vboxsf preemptively
      user:
        name: "{{ login }}"
        groups: vboxsf
        append: yes

    - name: source code control
      apt: name={{item}} state=present
      with_items:
        - git
        - subversion

    - name: media computation tools
      apt: name={{item}} state=present
      with_items:
        - audacity
        - blender
        - gimp
        - imagemagick
        - sox
        - vlc

    - name: additional C++ libraries and tools
      apt: name={{item}} state=present
      with_items:
        - autoconf
        - automake
        - clang
        - cmake
        - cscope
        - gobjc++
        - gobjc
        - libboost-all-dev
        - libfccp-dev
        - libglib2.0-dev
        - libgtest-dev
        - libgtkmm-3.0-dev
        - libsdl2-dev
        - libsdl2-gfx-dev
        - libsqlite3-dev
        - libssl-dev
        - lldb
        - meld
        # Not available for Ubuntu 16.04 LTS
        - nlohmann-json-dev
        - scons
        - sqlite3
        - valgrind

###############################################################################
# Mikhail Gofman's Packages
# point person: Mikhail Gofman
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Mikhail Gofman's Packages
      apt: name={{item}} state=present
      with_items:
        - tmate

###############################################################################
# CPSC 223J
# point person: Floyd Holliday
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223J Java environment
      apt: name={{item}} state=present
      with_items:
        - geany
        - gthumb
        - netbeans
        - openjdk-8-jdk
        - openjdk-8-jre

###############################################################################
# CPSC 223P
# point person: Michael Shafae
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223P Python environment
      apt: name={{item}} state=present
      with_items:
        - python
        - python-dev
        - python-pip
        - python-virtualenv
        - python3
        - python3-dev
        - python3-pip
        - virtualenvwrapper

###############################################################################
# CPSC 223N
# point person: Floyd Holliday
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223N C# environment
      apt: name={{item}} state=present
      with_items:
        - mono-complete
        - netbeans

###############################################################################
# CPSC 240
# point person: Floyd Holliday
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 240 assembly environment
      apt: name={{item}} state=present
      with_items:
        - intel2gas
        - nasm

###############################################################################
# CPSC 351
# point person: Michael Shafae
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 351 libraries
      apt: name={{item}} state=present
      with_items:
        - libreadline-dev
        - manpages-posix
        - manpages-posix-dev
        - glibc-doc


###############################################################################
# CPSC 484
# point person: Michael Shafae, Kevin Wortman
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 484 graphics environment
      apt: name={{item}} state=present
      with_items:
        - freeglut3-dev
        - libfreeimage-dev
        - libglu1-mesa-dev
        - libglew-dev
        - libgl1-mesa-dev
        - libopenctm-dev
        - libx11-dev
        - libxi-dev
        - libxrandr-dev
        - mesa-utils
        - mesa-utils-extra
        - openctm-tools
        - openctm-doc
        - python-openctm

###############################################################################
# CPSC 598, scholarly papers
# point person: Kevin Wortman
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: LaTeX
      apt: name=texlive-full state=present

###############################################################################
# cleanup
# point person: undergraduate committee
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: apt clean
      command: apt clean

...
