#!/usr/bin/env bash

## Written by dlime and Jared Dyreson ##
## Original source => https://gist.github.com/dlime/313f74fd23e4267c4a915086b84c7d3d ##

function perm_err_(){
  >&2 echo "[-] Not running as root, stop."
  exit 1
}

function build_(){
  CURRENT="$PWD"
  [[ "$(whoami)" != "root" ]] && perm_err_

  cd /tmp
  git clone https://github.com/google/googletest.git
  cd googletest
  mkdir build && cd build
  cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
  make -j8
  sudo make install
  sudo ldconfig
  cd "$CURRENT"
  test_

}

function test_(){
  # https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/ #
  [[ ! -d "/var/lib/tuffix/GoogleTest" ]] && exit
  cd googleTest
  cmake CMakeLists.txt
  make
  ./runTests
}

function aarch_err_(){
  >&2 echo "[-] Wrong OS, stop."
  exit 1
}

[[ ! "$(grep -i "ubuntu" /etc/os-release)" ]] && aarch_err_ || build_
