#!/usr/bin/env python3

import os
import shutil
import subprocess
import requests

GOOGLE_TEST_URL="https://github.com/google/googletest.git"
GOOGLE_DEST="google"

TEST_URL="https://github.com/ilxl-ppr/restaurant-bill.git"
TEST_DEST="test"

def build():
  os.chdir("/tmp")
  if(os.path.isdir(GOOGLE_DEST)):
    shutil.rmtree(GOOGLE_DEST)
  subprocess.run(['git', 'clone', GOOGLE_TEST_URL, GOOGLE_DEST])
  os.chdir(GOOGLE_DEST)
  subprocess.run(['cmake', 'CMakeLists.txt'])
  subprocess.run(['make', '-j8'])
  subprocess.run (['sudo', 'cp', '-r', 'googletest/include/.', '/usr/include'])
  subprocess.run(['sudo', 'cp', '-r', 'googlemock/include/.', '/usr/include'])
  subprocess.run(['sudo', 'cp', '-r', 'lib/.', '/usr/lib'])

def test():
  os.chdir("/tmp")
  if(os.path.isdir(TEST_DEST)):
    shutil.rmtree(TEST_DEST)
  subprocess.run(['git', 'clone', TEST_URL, TEST_DEST])
  os.chdir(TEST_DEST)
  shutil.copyfile("solution/main.cpp", "problem/main.cpp")
  os.chdir("problem")
  subprocess.run(['make', 'test'])

build()
test()
