#!/usr/bin/env python3

# standard library
import sys

# packages

# local modules
import tuffixlib
from TuffixInstallKeywords import *

if __name__ == '__main__':
    sys.exit(tuffixlib.main(tuffixlib.DEFAULT_BUILD_CONFIG, sys.argv))
