#####################################################################
# CPSC 481
# point person: Paul Salvador Inventado
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 481 Languages possibly used for AI projects
      apt: name={{item}} state=present
      with_items:
        - swi-prolog-x
        - swi-prolog-nox
        - sbcl
    - name: Eclipse installation
      unarchive:
        src: http://eclipse.bluemix.net/packages/2019-06/data/eclipse-java-2019-06-R-linux-gtk-x86_64.tar.gz
        dest: /opt
        remote_src: yes

    - name: Link Eclipse executable
      file:
        state: link
        src: /opt/eclipse/eclipse
        dest: /usr/local/bin/eclipse

#    - name: Create Eclipse menu item
#      copy:
#        src: eclipse.desktop
#        dest: /usr/share/applications/eclipse.desktop

