#####################################################################
# CPSC 484
# point person: Michael Shafae, Kevin Wortman
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 484 graphics environment
      apt: name={{item}} state=present
      with_items:
        - freeglut3-dev
        - libfreeimage-dev
        - libglu1-mesa-dev
        - libglew-dev
        - libgl1-mesa-dev
        - libopenctm-dev
        - libx11-dev
        - libxi-dev
        - libxrandr-dev
        - mesa-utils
        - mesa-utils-extra
        - openctm-tools
        - openctm-doc
        - python-openctm

